# Generated by Django 4.2.19 on 2025-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
