# Generated by Django 4.2.19 on 2025-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournamentplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
