# Generated by Django 4.2.18 on 2025-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Player'), ('playing', 'Game in Progress'), ('paused', 'Game Paused'), ('finished', 'Game Finished')], default='waiting', max_length=20),
        ),
    ]
