# Generated by Django 4.2.18 on 2025-01-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
