# Generated by Django 4.2.18 on 2025-01-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
