# Generated by Django 4.2.20 on 2025-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_active_user_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from42',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
